name: "Mo'Rx Photo"
favicon: null
layout_spectrum: 0.53738
typography_spectrum: 0.63271
title: MoRxPhoto
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1819'
    - '#ffffff'
    - '#312e2f'
    - '#b0afaf'
    - '#858485'
  brandStrength: 0.0625
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 0
purpose: []
