name: "Mo'Rx Photo"
favicon: null
layout_spectrum: 0.53738
typography_spectrum: 0.63271
title: "Mo'Rx Photo"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.875
  lightness: 0.0625
  saturation: 1
  rhythmicContrast: 0
purpose: []
